backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/images
public_folder: /img

collections:
  - name: "bakery"
    label: "Bakery"
    folder: "content/bakery"
    format: "frontmatter"
    create: true
    identifier_field: name
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Price", name: "price", widget: "number" }
