backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "images"
public_folder: "images"

site_url: https://mrsodonoghue.netlify.app
display_url: https://mrsodonoghue.netlify.app
logo_url: https://mrsodonoghue.netlify.app/ModBadge.png

collections:
  - name: "bakery"
    label: "Bakery"
    folder: "content/bakery"
    media_folder: ""
    format: "frontmatter"
    create: true
    identifier_field: name
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {
          label: "Order",
          name: "order",
          widget: "number",
          value_type: "int",
          default: 00,
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Description",
          name: "description",
          widget: "markdown",
          required: false,
        }
      - { label: "Price", name: "price", widget: "number" }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          media_folder: "/content/bakery",
          public_folder: "/content/bakery/",
          choose_url: true,
          required: false,
        }
