backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "static/images"
public_folder: "/images"

site_url: https://mrsodonoghue.netlify.app
display_url: https://mrsodonoghue.netlify.app
logo_url: https://mrsodonoghue.netlify.app/assets/images/ModBadge.png

collections:
  - name: "bakery"
    label: "Bakery"
    folder: "content/bakery"
    format: "frontmatter"
    create: true
    identifier_field: name
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Price", name: "price", widget: "number" }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          choose_url: true,
          media_folder: "images",
          required: false,
        }
